lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-scalepopgen_logo_light.png
  - docs/images/nf-core-scalepopgen_logo_light.png
  - docs/images/nf-core-scalepopgen_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - conf/igenomes.config
  - conf/igenomes.config
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-scalepopgen_logo_light.png
  - docs/images/nf-core-scalepopgen_logo_light.png
  - docs/images/nf-core-scalepopgen_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - process.cpus
  - process.memory
  - process.time
  - custom_config
repository_type: pipeline
template:
  prefix: popgen48
  skip:
  - igenomes
  - nf_core_configs
